[book]
authors = ["Ilona Bozhe"]
language = "en"
multilingual = false
src = "src"
title = "Parprog course notes"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/warmte/parprog-notes"
